### ISSUE TITLE
Cannot capture multiple words at once

### ISSUE THREAD

**Issue by Jared-Caraan** [ManivannanMurugavel/spacy-ner-annotator#1]
Hi,

When I try to highlight a sentence. It would state an error saying: 'Please select entity inside content'

What I want to do is input the sentence as a whole.

![image](https://user-images.githubusercontent.com/29474397/59027850-abc31a80-888c-11e9-912c-9c85d0be9d49.png)

**Comment by ManivannanIkomet** [comment]
Hi @Jared-Caraan ,
Please select any one class name before when you click next content

**Comment by ManivannanMurugavel** [comment]
Solved
