### ISSUE TITLE
Graphic problem when scrolling down the text in the Content Section

### ISSUE THREAD

**Issue by Zast996** [ManivannanMurugavel/spacy-ner-annotator#12]
Hi, firstly thank you for your work.
When I put in the Content window a text which is longer than the window and press the save button, when scrolling down the text, there is a graphic bug that overlap the text.
I attached a photo to show the problem.
![problem](https://user-images.githubusercontent.com/62074263/100914237-13364680-34d3-11eb-9a07-a07253a9787d.png)

**Comment by ManivannanMurugavel** [comment]
Hi @Zast996 ,

The bug is resolved and please test it.
once resolved, close the issue..

**Comment by Zast996** [comment]
Many thanks. I have done some test and it seems to work fine
