### ISSUE TITLE
add keyboard shortcuts

### ISSUE THREAD

**Issue by apzl** [ManivannanMurugavel/spacy-ner-annotator#14]
keyboard shortcuts to choose class, skip, next content and complete.

**Comment by ManivannanMurugavel** [comment]
Hi @apzl ,

I will add and let you know once completed..

**Comment by apzl** [comment]
are you already working on it? else I'd like to contribute

**Comment by ManivannanMurugavel** [comment]
Hi @apzl ,
Welcome to your contribution
