### ISSUE TITLE
Labels disappears if clicking the "Edit" button

### ISSUE THREAD

**Issue by Zast996** [ManivannanMurugavel/spacy-ner-annotator#15]
Hi, 
suppose I have labeled some text.
At some point I want to edit it for some reason.
If click on the Edit button and then Save, the labels disappear.
Is this a problem or an expected behaviour?
In addition, when i delete some text, it doesn't desappear until I don't click the "Save" button
Many thanks in advance

**Comment by ManivannanMurugavel** [comment]
Hi @Zast996 ,

That is the condition.
When you edit and save, the previous annotation will gone.

**Comment by Zast996** [comment]
Thanks @ManivannanMurugavel 
There is the following issue too:
when i delete some text, it doesn't disappear until I don't click the "Save" button
Should I open another issue?

**Comment by ManivannanMurugavel** [comment]
Hi @Zast996,
Do you have any issue after save, then raise the issue. Otherwise that's my restriction..
