### ISSUE TITLE
How do we start the server

### ISSUE THREAD

**Issue by skprasadu** [ManivannanMurugavel/spacy-ner-annotator#3]
I have a basic question, how do you start the server, so that we can open in the webpage and train the data.

The youtube video is in silent mode, so I couldnt hear what you were telling.

**Comment by ManivannanMurugavel** [comment]
Hi
I can't understand your response.
What do you mean the server?

**Comment by georgenv** [comment]
Hi,
I understood his question. @skprasadu you have to perform the following steps:

1 - Clone the repository
2 - Enter in the spacy-ner-annotator directory
3 - Open the terminal in the current directory
4 - Run the command: `python3 -m http.server [port_number]` (Python 3) or `python -m SimpleHTTPServer [port_number]` (Python 2)
5 - Access your localhost:port_number using a browser

Regards,
George

**Comment by ManivannanMurugavel** [comment]
Nice @george
