### ISSUE TITLE
Annotator is taking the same indices if the two entities have same value

### ISSUE THREAD

**Issue by pranavinu** [ManivannanMurugavel/spacy-ner-annotator#6]
For example, if the text is : Start Date/Time: 4/12/2019 2:00:00 AM EASTERN End Date/Time: 4/12/2019 6:00:00 AM EASTERN Description: Section Roll Expected Impact: 4 Hours Contact Information: Call the SCCC, and reference RFC-0051317 Thank you, Cincinnati Bell Change. It is giving the following output:
 "entities": [[627,636,"StartDate"],[637,647,"StartTime"],[627,636,"EndDate"],[681,691,"EndTime"],[648,655,"TimeZone"].
Here the value of start and end date is same (4/12/2019). So, it is taking the same indices for both the indices. Please check it. Thank You in advance

**Comment by ManivannanMurugavel** [comment]
I know the issue
I am working on that

**Comment by pranavinu** [comment]
Okay! Please let me know after resolving the issue. Thank You :)

**Comment by ManivannanIkomet** [comment]
Hi @pranavinu 
In **assets/js/project.js** file, comment the line num 167
```
//entities.push([iniidx,(iniidx+lgth),$(this).text()]);
```
Paste the below three lines
```
var start = selection.anchorOffset;
var end = selection.focusOffset;
entities.push([start,end,$(this).text()]);
```
**Condition**:
When you the add these lines
you can annotate the buttom-up approach. That means you annotate the words from bottom to up.

**Comment by Wadaboa** [comment]
The above mentioned solution isn't working either. 
Could you please provide an alternative? Thank you.

**Comment by ManivannanMurugavel** [comment]
Hi @pranavinu and @Wadaboa 

I completed this issue and do you want to test?

**Comment by Wadaboa** [comment]
I see no new commits nor pull requests @ManivannanMurugavel, how did you complete the issue?

If you are referring to the solution you mentioned above, I tested it several months ago and I was having the same kind of problems.

**Comment by ManivannanMurugavel** [comment]
Hi @Wadaboa ,
I commited the v2.0 beta tesing code. Please try and let me know if you facing any issue

**Comment by Wadaboa** [comment]
From a quick experiment, it seems to work fine now.
