### ISSUE TITLE
TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by kingsley351** [ManivannanMurugavel/spacy-ner-annotator#8]
Thank you for your annotator. 

But when I executed train.py after copying text into TRAIN_DATA variable, I got this Error 

File ".\train.py", TypeError: 'tuple' object is not callable. 

I am working with python 3.7.

Could you please help me ?

**Comment by ManivannanMurugavel** [comment]
Hi,
TRAIN_DATA is list of tuples.
Please check the datatype if it's string not working

**Comment by kingsley351** [comment]
Thank you, I have fixed that but actually I have another error 

TypeError: list indices must be integers or slices, not tuple

**Comment by ManivannanMurugavel** [comment]
Send me your json
